version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
before_build:
- ps: nuget restore src/Our.Umbraco.HealthChecks.Web.sln
build:
  project: src/Our.Umbraco.HealthChecks/Our.Umbraco.HealthChecks.csproj
  publish_nuget: true
  verbosity: minimal
